### ISSUE TITLE
VDSL Error statistics don't seem to be correct

### ISSUE THREAD

**Issue by fatfurrycat** [poempelfox/vigor130#4]
Hi, 

Just wanted to say thanks for the great Munin plugin.
I'm using it with a Vigor 130, and the data appears to be parsed correctly, as below:

[root@lenovo-p50 Draytek]# ./munin-plugin-vigor130-telnet.pl 
multigraph vig130_datarates
attdnrate.value 57962392
attuprate.value 17161686
curdnrate.value 58029000
curuprate.value 17084000
multigraph vig130_snrmargins
snrmargindn.value 6
snrmarginup.value 6
multigraph vig130_attenuation
attenuationdn.value 13
attenuationup.value 14
multigraph vig130_errors1_dn
crcerrsdn.value 9
fecsdn.value 90
esdn.value 8
sesdn.value 0
lossdn.value 0
uasdn.value 41
multigraph vig130_errors1_up
crcerrsup.value 23274
fecsup.value 1984634515
esup.value 16328
sesup.value 33
lossup.value 306
uasup.value 18989

However, when the error values are plotted and values display, the output seems inconsistent with the values shown above. 

For example, there are 9 downstream CRC errors shown in the output above, but the value shown for the current value is zero. 

Also, with FEC errors, the current value shown above is 90, yet the value display under the graph for current is 33.33u. The screenshot attached shows something different again, as another 5 minute update interval had occurred. 

I'm just wondering if you could explain this mismatch, and also what units are being employed here, as they don't seem consistent (which I think is mentioned in the perl). 

Thanks, 

Andy.
![Error Graphs](https://user-images.githubusercontent.com/4748271/77120736-71002c80-6a31-11ea-9aa5-486e47ae3e5b.png)

**Comment by poempelfox** [comment]
> For example, there are 9 downstream CRC errors shown in the output above, but the value shown for the current value is zero.
> I'm just wondering if you could explain this mismatch

"CRC errors" and the other error counters are what RRD calls COUNTERS, that is the value you get is the number of CRC errors that have occoured _since the modem booted_. Now there are two ways to draw that: If you'd draw the absolute number, you'd get a curve that permanently goes up, every time an CRC error occours it would go a tiny bit higher, until you reboot the vigor, then it would drop down to zero again. I don't think that would be very useful. What you see instead is a graph that shows how much the number increased in the last 5 minutes, i.e. how many new CRC errors have occoured in these last 5 minutes (5 minutes is the interval at which munin queries values).

> Also, with FEC errors, the current value shown above is 90,
> yet the value display under the graph for current is 33.33u.

I don't see 33.33u in the image you posted, but 6.6m. To explain that: There have been 90 errors total since the modem was booted. There have been two errors in the last 5 minute interval that munin queried. Why does it show 6.6m then? Because the unit munin shows is always "per second". 2 errors divided by 300 seconds (5 minutes) = 0.00667 errors per second = 6.6 mili-errors per second.
If you want larger values, modify the plugin to multiply all the values by 300 when printing, then in the 5 minute graph you'd see "errors per graph interval". Unfortunately, then the numbers are no longer a useful unit in any of the longer-term graphs.

> also what units are being employed here, as they don't seem consistent

I don't develop DSL standards or modems, so cannot give an authoritative answer on that, but in most cases it seems pretty obvious anyways. For example, CRC errors quite clearly is the number of CRC errors, each error increases the counter by 1. For others, it's a bit more complicated. For example, LOSS is "Loss Of Signal Seconds". That shouldn't increase by 1 everytime you lose the DSL signal, but by 1 for every second the signal is gone. So if you're disconnected permanently, that value should increase by 300 in 5 minutes - and consequently, I'd expect the graph to show a constant "1" line.
