### ISSUE TITLE
Vigor165 plotting some graphs not working

### ISSUE THREAD

**Issue by bondskin** [poempelfox/vigor130#5]
Hi all,

First of all thank you for this plugin.
I am using it with a Vigor 165 and it delivers results.
If I run the script manually, I also get CRC values.
```
multigraph vig165_datarates
attdnrate.value 291592448
attuprate.value 47677000
curdnrate.value 287722000
curuprate.value 46719000
multigraph vig165_snrmargins
snrmargindn.value 5
snrmarginup.value 7
multigraph vig165_attenuation
attenuationdn.value 14
attenuationup.value 8
multigraph vig165_errors1_dn
crcerrsdn.value 17
fecsdn.value 0
esdn.value 11
sesdn.value 0
lossdn.value 0
uasdn.value 99
multigraph vig165_errors1_up
crcerrsup.value 754
fecsup.value 0
esup.value 230
sesup.value 42
lossup.value 4
uasup.value 18109
```

However, the respective graphs are not drawn or showing 0 values.
Any idea how to fix this please?

<img width="530" alt="Bildschirmfoto 2021-05-09 um 11 16 30" src="https://user-images.githubusercontent.com/55050117/117566637-0936f600-b0b8-11eb-996d-6cc5a78a3569.png">

**Comment by poempelfox** [comment]
I'm not sure there even is anything to fix, my gut feeling tells me this might just be a misunderstanding?
What you see when you run the script manually is what the vigor returns, which in the case of CRC errors is the total number of CRC errors that have occoured since you booted the Vigor. That however is not what munin draws, what munin draws is how much _new_ errors have occoured since the last run (with runs usually occouring every 5 minutes). If you run the plugin manually 5 minutes apart and the CRC numbers do not increase between these two runs, then it's absolutely correct that munin draws a "0" for that interval, simply because no CRC errors have occoured in that interval.

**Comment by bondskin** [comment]
@poempelfox , well, that would be a good explanation.
However, other values / graphs, e.g. SNR Attentuation or Data Rate are plotting exactly the values as reported when I run the script manually.

So I will wait a few days to see if errors graph is changing.
Thanks for chiming in here.

**Comment by poempelfox** [comment]
That is because these are different types of values, in the case of e.g. data rate what the modem reports already is the current rate and munin does no further processing of that value because there is no need, while for e.g. CRC-errors what the modem reports is just a counter that increases with every error, and it's munins job to figure out on its own how much it changes over time. These types are 'gauge' vs 'derive' in munin or rrdtool speak. You can see which is which either by looking at the sourcecode; by running the plugin with the parameter 'config'; or in the munin webinterface by clicking a graph: below the graph there will be a table, and there is a column 'type'.
